In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df = df.drop(["PassengerId", "Name", "SibSp", "Parch", "Ticket", "Cabin", "Embarked"], axis=1)
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [5]:
target = df.Survived
inputs= df.drop("Survived", axis=1)

In [6]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head()

   female   male
0   False   True
1    True  False
2    True  False
3    True  False
4   False   True

In [7]:
inputs = pd.concat([inputs, dummies], axis="columns")
inputs.head()

   Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False
3       1  female  35.0  53.1000    True  False
4       3    male  35.0   8.0500   False   True

In [9]:
inputs = inputs.drop("Sex", axis="columns")
inputs.head()

   Pclass   Age     Fare  female   male
0       3  22.0   7.2500   False   True
1       1  38.0  71.2833    True  False
2       3  26.0   7.9250    True  False
3       1  35.0  53.1000    True  False
4       3  35.0   8.0500   False   True

In [10]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [11]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [13]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())

In [14]:
inputs.columns[inputs.isna().any()]

Index([], dtype='object')

In [40]:
# Splitting the data into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(inputs, target, test_size=0.1, stratify=target, random_state=42)

In [41]:
inputs.shape, X_train.shape, X_test.shape

((891, 5), (801, 5), (90, 5))

In [42]:
# Gaussian Navie bias model
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [43]:
model.fit(X_train, Y_train)

GaussianNB()

In [44]:
model.score(X_train, Y_train)

0.7865168539325843

In [45]:
model.score(X_test, Y_test)

0.7555555555555555

In [33]:
X_test[:10]

     Pclass        Age      Fare  female   male
595       3  36.000000   24.1500   False   True
540       1  36.000000   71.0000    True  False
593       3  29.699118    7.7500    True  False
8         3  27.000000   11.1333    True  False
732       2  29.699118    0.0000   False   True
689       1  15.000000  211.3375    True  False
406       3  51.000000    7.7500   False   True
805       3  31.000000    7.7750   False   True
762       3  20.000000    7.2292   False   True
523       1  44.000000   57.9792    True  False

In [34]:
Y_test[:10]

595    0
540    1
593    0
8      1
732    0
689    1
406    0
805    0
762    1
523    1
Name: Survived, dtype: int64

In [46]:
model.predict_proba(X_test[:10])

array([[0.01212325, 0.98787675],
       [0.99013254, 0.00986746],
       [0.98803815, 0.01196185],
       [0.05658678, 0.94341322],
       [0.99062636, 0.00937364],
       [0.98119384, 0.01880616],
       [0.99066371, 0.00933629],
       [0.06118371, 0.93881629],
       [0.02359648, 0.97640352],
       [0.98925244, 0.01074756]])